### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by enricribas** [alexcurtis/react-treebeard#1]
Error: Command failed: /bin/sh -c npm install --save react-treebeard

Unsupported URL Type: github:alexcurtis/react-utils

Runnng npm 2.5.1

I'm guessing the new format is part of npm 3.0? Or is this a typo in your package.json?

**Comment by alexcurtis** [comment]
@enricribas Ah! Excellent find. Thanks! I'll get this into the build asap.

**Comment by alexcurtis** [comment]
@enricribas I have published `1.0.10`. This should now support your npm version. Please let me know if you have any more problems.

**Comment by enricribas** [comment]
Thanks, will give it a try again!
