### ISSUE TITLE
AutoScroll to active node

### ISSUE THREAD

**Issue by bkniffler** [alexcurtis/react-treebeard#10]
Hey again, 
I thought it might be useful if you could declare `node.active` on a node and have react-treebeard autoscroll on initial load, to get the active item into the view.

Would you consider something like that? 

This is a raw workaround I would use without modifying your library. 

```javascript
var el = document.getElementById(this.activeElement);
document.getElementById(this.activeElement).scrollIntoView();

Header: props => {
   if(props.node.active){
      this.activeElement = 'tree-item-' + props.node.id;
   }
   return (
      <div style={props.style.base} id={'tree-item-' + props.node.id}>
         {...}
      </div>
   );
}
```

**Comment by alexcurtis** [comment]
@bkniffler I'm not sure that having treebeard control the window scroll is a good idea. But maybe we should make some additions, so you don't have to create a custom header etc to perform this task.

**Comment by bkniffler** [comment]
I've thought a bit more about it, you're right. treebeard should stay lightweight and this really is an edge case. I'm happy with overwriting the header to implement this functionality and I think this should be the way to implement such custom behavior. 

I've thought about if plugins would make sense, but in the end, this is only a tree component with limited complexity, this would be overkill. Feel free to close this issue, or keep it open if you got ideas and thoughts about this.
