### ISSUE TITLE
Add support for react 16 in peerdeps

### ISSUE THREAD

**Issue by brucewpaul** [alexcurtis/react-treebeard#106]
what is the timeline for releasing the expanded peerdeps? the pr (https://github.com/alexcurtis/react-treebeard/pull/102) was merged a bit ago

**Comment by MichaelDeBoey** [comment]
@brucewpaul I'll try to cut a release tonight, so this is available for everyone. 🙂

**Comment by brucewpaul** [comment]
awesome thanks!

**Comment by leeran88** [comment]
Hey @MichaelDeBoey, any updates regarding the release ?

**Comment by MichaelDeBoey** [comment]
Released in [`v2.1.0`](https://github.com/alexcurtis/react-treebeard/releases/tag/v2.1.0) as of now! 🙂
