### ISSUE TITLE
Can't resolve './lib/index' 

### ISSUE THREAD

**Issue by bindalkumar** [alexcurtis/react-treebeard#108]
@alexcurtis @MichaelDeBoey  getting following error while using latest version
```
Can't resolve './lib/index' 
```
I checked that no lib folder exists in this repo. Please help

Please find latest repo screenshot

![err](https://user-images.githubusercontent.com/25037450/34107916-01cf2d2e-e424-11e7-893f-237f0071f980.png)

**Comment by igor-dv** [comment]
`lib` is the directory where babel put its output. You can `npm run lib` it to run the babel. Look at the  `package.json` scripts.

**Comment by bindalkumar** [comment]
So after installing this package by running ``npm install react-treebeard --save`` command I will have to run ``npm run lib`` manually?

**Comment by igor-dv** [comment]
Ah. I thought you are talking about taking the fork. For this case, there is `prepublish` script that runs before publishing to npm.

**Comment by bindalkumar** [comment]
Thanks @igor-dv for your help. All doubts are clear now.
