### ISSUE TITLE
View toggling But data Variable Is Not Modified

### ISSUE THREAD

**Issue by gbmhunter** [alexcurtis/react-treebeard#14]
I commented out all code in the `onToggle` event handler (and hence the data variable does not get modified), yet the view still toggles as normal.

As far as I can understand, the view is driven from the `data` variable, so the view should only toggle if the corresponding `toggled` parameter in the `data` variable changes?

**Comment by alexcurtis** [comment]
@gbmhunter What I might do is put in a 'data-driven' boolean flag on the top level treebeard props. That can be used when you want the `toggled` state to be driven completely via the data prop. Then have the fallback (like it currently works using component state) -- when people don't want to handle this and just want a quick default treeview. Does that sound reasonable?

**Comment by alexcurtis** [comment]
Or maybe Its best to simplify it right down and make it completely data driven. Which is more react-ish. It would however, mean everyone has to define an onToggle callback to get simple things like toggling the drawer to work.

**Comment by alexcurtis** [comment]
@gbmhunter I have reworked treebeard to be completely data driven. I think its the best way to ensure its easy to keep extending functionality in the future. It's currently in master. Could you please try it out and see if it works well for you? Thanks!

**Comment by gbmhunter** [comment]
Hi @alexcurtis ,

I have attempted to pull the latest master on GitHub with the command:

````
npm install git+https://github.com/alexcurtis/react-treebeard/react-treebeard.git --save
````

I had a look at some of the files after my attempted update, and the update seemed to have worked. However the view is still toggling while `onToggle()` is empty.t

I also did `npm rm react-treebeard --save` first.

What's going on here?

**Comment by alexcurtis** [comment]
@gbmhunter I'm not exactly sure what happening in your project. But in the project example, if you clear out `onToggle` then it definitely doesn't toggle. Are you using a cached version?

**Comment by alexcurtis** [comment]
@gbmhunter Just thought. If you are using the master, you will need to compile down the lib before use. When I push to npm, this is automatic. But for now, whilst you test master, you will need to do this step.
Simply go into the directory and build using `npm run lib`. Make sure you have all the dev dependencies.

**Comment by gbmhunter** [comment]
Woah, I'm running on a Windows machine and having many difficulties trying to install the dev dependencies. Many errors are being thrown when trying to run `npm install -d` inside the react-treebeard folder. Note that I'm not a JavaScript programmer by trade and so it probably a little behind the ball when it comes to fixing this stuff.

**Comment by gbmhunter** [comment]
I am stuck in a loop with npm errors stating "Attempt to unlock <npm module path>, which hasn't been locked".

**Comment by alexcurtis** [comment]
@gbmhunter. I'll push this out to a npm release today. I'm quite happy with it being data-driven. But its a breaking change, so I'll bump up the version to 1.x.0. I'm in the middle of a decorator refactor, so once thats done, I'll push everything to  a new release.

**Comment by alexcurtis** [comment]
@gbmhunter. I have release `1.1.0` to npm. This is a full data-driven release. No internal state. Hopefully it works as expected now.

**Comment by gbmhunter** [comment]
@alexcurtis works perfectly now thank you! BTW, do you have a donate button or something similar? I'm super impressed by the effort you've put into this open-source library.

**Comment by alexcurtis** [comment]
@gbmhunter Thank you for your amazing support! I've added a Pledgie donate button to the Readme.
