### ISSUE TITLE
Disable animations

### ISSUE THREAD

**Issue by bkniffler** [alexcurtis/react-treebeard#15]
Hey, 
Animations are great, but sometimes apps feel a bit snappier without these. I know we can overwrite them with some animation object like below, but just handing `animations={false}` or `animations={null}` would be a bit more intuitiv and comfortable.

```jsx
<Treebeard animations={false}/>
```

Thats whats currently necessary:

```jsx
var animations = {
   toggle: (state) => {
      return {};
   },
   drawer: (/* state */) => {
      return {
         enter: {},
         leave: {}
      };
   }
}
<Treebeard animations={Animations}/>
```

**Comment by alexcurtis** [comment]
@bkniffler Sounds good to me. I'll add them into the current work batch. Thank you!

**Comment by alexcurtis** [comment]
@bkniffler There is a change to optimise this further, by not rendering any of the velocity components when this is false. Which is pretty neat.

**Comment by alexcurtis** [comment]
@bkniffler. This should be in `1.1.0`. As suggested, set `animations` to `false`.

**Comment by bkniffler** [comment]
Great, thanks! Works as expected.
