### ISSUE TITLE
transfer props

### ISSUE THREAD

**Issue by TimYi** [alexcurtis/react-treebeard#16]
https://facebook.github.io/react/docs/transferring-props.html
I think in TreeBeard render method, add a parameter to pass on extra props to all nodes may be a good idea. I know I can write them in my nodes, but sometimes It's not elegant.

You can use JSX spread attributes to merge the old props with additional values:

<Component {...this.props} more="values" />

**Comment by alexcurtis** [comment]
@TimYi . Yeah, that sounds like a good idea. Any chance you could create a quick pull request? It should be a quick addition. Thanks.

**Comment by popasquat89** [comment]
@alexcurtis Anyway that we can get one of the 3 pr's landed that solves these issues? This would come in handy in several use cases.
