### ISSUE TITLE
errors whe trying the example

### ISSUE THREAD

**Issue by Bramas** [alexcurtis/react-treebeard#2]
Hello and thanks for the great work!!

I tried today just to render the example found in the readme, but I have some issues.
Expanding a node works well but fire this error:

        Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

but I cannot collapse a node and I get the following errors from React:

        Uncaught TypeError: Cannot read property 'componentWillEnter' of undefined

I use the last version of React, with browserify and reactify --es6

Maybe you can give me a hint on where the errors come from?
Thanks

**Comment by alexcurtis** [comment]
@Bramas Hi. Which version of Node + NPM are you using? It might be that you have 2 react libs in your dependency tree and I need to modify the dependencies in the project.

**Comment by alexcurtis** [comment]
@Bramas It might be work running npm dedupe first to see if that solves the issue: https://docs.npmjs.com/cli/dedupe

**Comment by Bramas** [comment]
Thanks for your help.

First I removed reactify (which is deprecated) to use babel. Here is my package.json:

    {
        //... name and desc
      "scripts": {
        "start": "browserify -t [ babelify --presets [ es2015 react ] ] -t debowerify ./index.js > ./bundle.js"
      },
      "devDependencies": {
        "babel-preset-es2015": "^6.1.18",
        "babel-preset-react": "^6.1.18",
        "babelify": "^7.2.0",
        "react-addons-test-utils": "^0.14.3",
        "react": "^0.14.3",
        "react-dom": "^0.14.3",
        "browserify": "*",
        "debowerify": "*",
        "react-treebeard": "*"
      }
    }

But I still get the error.

@alexcurtis I tried to run dedupe but it returns nothing.

I will try to reduce even more my project (which is quite already small) to isolate the problem (because here debowerify can be the reason maybe)

**Comment by Bramas** [comment]
I removed debowerify.
And index.js only contains **exactly** the example in the readme.

Same error

**Comment by Bramas** [comment]
I forgot to mention: 
npm version: 2.14.7
node version: 4.2.2

**Comment by alexcurtis** [comment]
After a quick Google. It might be a well known issue with browserify. The suggested fix is to use the browserify-resolutions plugin to dedupe react at the browserify level. Could you give that a quick go to see if it removes the errors. If not, I'll dig a little deeper into my project package and see if its my end. https://www.npmjs.com/package/browserify-resolutions

**Comment by alexcurtis** [comment]
@Bramas. Would it be possible for you to repo this project into github so I can try to fix it?

**Comment by Bramas** [comment]
I removed react-treebeard and reinstalled it and it works!

I don't know exactly what caused the problem. I mean it surely comes from conflicting instance of react as you said but where do they come from, i don't know (but certainly not from treebeard!!)

Thanks again for your help and for the great project, now I can have fun with it!!

**Comment by alexcurtis** [comment]
@Bramas Awesome. I thought it would be something like that. Thanks for the support! If you have an ideas / fixes / improvements, please let me know and i'll try and make it happen. Or, if you wanted to contribute, that would also be pretty cool!

**Comment by bkniffler** [comment]
I had similar issues, react-treebeard only showing the symptoms, not being the cause. Double and triple check for duplicate react instances.

**Comment by alexcurtis** [comment]
@bkniffler I'm struggling to replicate this here. Do you have a small test project that errors that I can see?

**Comment by bkniffler** [comment]
Oh, sorry, I wasn't clear. I wanted to confirm the previous comments and suggest that everyone who sees this issue should double check for duplicate react instances within their own project!

**Comment by alexcurtis** [comment]
@bkniffler Ah ok cool. :-)

**Comment by dan3721** [comment]
Upgrading NPM to 3.10.8 via `npm install -g npm` resolved the issue for me.
