### ISSUE TITLE
How can i set my customstyle.js from Treebeard style prop?

### ISSUE THREAD

**Issue by ZiyaKorol** [alexcurtis/react-treebeard#21]
When i try to set my customstyle.js from treebeard style prop, i got this error.
Thanks.

![exc1](https://cloud.githubusercontent.com/assets/8333961/12675765/3e19b244-c695-11e5-9fbb-d0294e377827.PNG)
![exc2](https://cloud.githubusercontent.com/assets/8333961/12675738/0b5fa2fa-c695-11e5-95e7-21f6b016c70c.PNG)
![exc3](https://cloud.githubusercontent.com/assets/8333961/12675739/0bf940b8-c695-11e5-9241-ad353a2c8429.PNG)

**Comment by eyala-stratoscale** [comment]
@ZiyaKorol I think that when you try to customize style here it needs the full list of properties like the default styles in default.js.
I suggest taking the default theme and changing only what you want to change.
Also, pass style={style} when you do that.

**Comment by alexcurtis** [comment]
@eyala-stratoscale Yep, spot on. Thanks!
