### ISSUE TITLE
Decorators aren't passed to children

### ISSUE THREAD

**Issue by eyala-stratoscale** [alexcurtis/react-treebeard#22]
Hey,
Thanks for the very good looking tree view. 

I found an issue when using decorators. The decorators are only applied to the level you put them on and don't get passed to the children.
Which seems a bit weird to me. 
Is that intended or a bug ? 

Say I do : 
`const decorators = {
  Loading: (props) => {
    return (
      <div>
        LOADING!
      </div>
    )
  },
};`

`const data = {
    name: 'Root',
    toggled: true,
    active: false,
    decorators: decorators,
    children: [
        {
            name: 'parent',
            children: [
                { name: 'child1' },
                { name: 'child2' }
            ]
        },
        {
            name: 'loading parent',
            loading: true,
            children: []
        },
        {
            name: 'parent',
            children: [
                {
                    name: 'nested parent',
                    children: [
                        { name: 'nested child 1' },
                        { name: 'nested child 2' }
                    ]
                }
            ]
        }
    ]
};`

loading parent child will still look like the default "loading..." and not the decorated one.
If I put loading:true on root only root will have the loading decorator.

**Comment by alexcurtis** [comment]
Hi. The data decorators are applied on a single level intentionally. This is a special use-case, where you want to associate a specific decorator with a specific item of data.

If you want to blanket change the decorators, insert them as props when declaring the Treebeard Element:
```
<Treebeard data={...} decorators={decorators}/>
```

**Comment by eyala-stratoscale** [comment]
doesn't work for me. I tried 
`const decorators = {
  Loading: (props) => {
    return (
      <div>
        LOADING!
      </div>
    )
  },
  Header: (props) => {
    return (
      <span style={props.style}>
        {props.node.name} Blat
      </span>
    );
  },
};`

and putting it on the component like you suggested , however I get 
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `NodeHeader`.
and Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `NodeHeader`.

**Comment by alexcurtis** [comment]
you currently need to extend the default decorators or make sure you create them all from scratch. Please see the example.

**Comment by eyala-stratoscale** [comment]
ok, will give it a try
