### ISSUE TITLE
Quick start problem

### ISSUE THREAD

**Issue by ksnyder** [alexcurtis/react-treebeard#27]
Hi -- We're doing a quick evaluation, and lifted the code from the Readme Quick Start.  It works correctly on first render, but clicks to toggle do not change the DOM or styles.  I verified that this.onToggle is called, and the toggled state of individual nodes does change, but there are no changes to what's rendered.  If I change the initial 'toggled' values in the data prop sent in, the initial render correctly reflects the toggled state.  I built the ./example app and it works fine.  

Wondering if there is some piece missing from the Quick Start instructions.

**Comment by alexcurtis** [comment]
Was everything ok? I'd be interested in improving the quick start example if it was working correctly.

**Comment by TimNZ** [comment]
I'm having the same problem incorporating sample code into my React 0.15 app
Renders but clicking nodes does nothing - can't expand/collapse, active node not highlighted.

**Comment by sherylj** [comment]
Hi @alexcurtis, I'm having the same problem with the Quick Start. It seems to correctly render the data, but the clicks to toggle doesn't change the nodes or styles. Wondering if I missed some step or dependencies.

**Comment by rameshvishnoi90904** [comment]
I am having similar problem, click on one item expands next item
