### ISSUE TITLE
Need  Checkboxes

### ISSUE THREAD

**Issue by Miteshdv** [alexcurtis/react-treebeard#28]
Can we put checkboxes inside the tree ?

**Comment by alexcurtis** [comment]
@Miteshdv Yep, you certainly can. You need to create your own decorators. Please see the readme.

**Comment by Miteshdv** [comment]
I will try thanks

**Comment by Demon2** [comment]
@Miteshdv  Have you tried it, I can see your code

**Comment by kamarajuPrathi** [comment]
@Miteshdv hey did you get it working with check box by any chance ?

**Comment by Miteshdv** [comment]
Yeah .. I used some other component ..

**Comment by A1Guy** [comment]
Can anyone please provide me an example? Do i have to completely rewrite decorator object or can i extend the existing one to 'add' checkbox to default implementation?
