### ISSUE TITLE
How is the background colour of the last clicked on element changed?

### ISSUE THREAD

**Issue by gbmhunter** [alexcurtis/react-treebeard#3]
I notice the background colour of the last clicked item changes on the example.

![image](https://cloud.githubusercontent.com/assets/2396869/11394688/7a520f9c-93cb-11e5-912b-743466581c21.png)

I am trying to get a similar effect using treebeard in my project, however can't seem to get this to work (it doesn't seem to highlight by default), given the parameters available in the `style` variable.

This is what my modification of the example looks like ("Basic" has been clicked on):

![image](https://cloud.githubusercontent.com/assets/2396869/11394740/d3398ff4-93cb-11e5-8778-dc7824445122.png)

**Comment by alexcurtis** [comment]
Hi. Could I please see your style object for `node`? There should be a object in there called `activeLink` and that sets the backgroundColor.

**Comment by gbmhunter** [comment]
Here it is:

![image](https://cloud.githubusercontent.com/assets/2396869/11395007/5aa538fc-93cd-11e5-9a0e-494414efc274.png)

I know this style variable is being loaded in correctly as other parameters do have an effect.

**Comment by alexcurtis** [comment]
`activeLink` requires the props `props.node.active` to be set. Could you set a breakpoint in components/header.js line 15. When you click a node please can you see if that is being set to true and re-rendered.

**Comment by gbmhunter** [comment]
`this.props.node.active` seems to be undefined.

![image](https://cloud.githubusercontent.com/assets/2396869/11395321/31a82fc0-93cf-11e5-92ba-9919520294a2.png)

This is caught after clicking on a node. It caught two passes through this part of code after clicking, and both where undefined.

**Comment by alexcurtis** [comment]
Are you setting `node.active` in the `onToggle` handler, like in the example? Nodes do not control this within their own state, its purely data driven from the top level.

**Comment by gbmhunter** [comment]
Ahhh, I think you have hinted towards the issue. I am setting node.active, but I switched the data source from the example data variable to a data source within my application state variable (I'm using the Redux framework if you are familiar with that?). Hence I'm updating the wrong data set. I'm surprised the open/close toggling of nodes still works...

Anyway, I know what I have to do now, create some actions which are dispatched inside those event handlers which modify the internal state in Redux, and it should then update fine. Thanks!

**Comment by alexcurtis** [comment]
@gbmhunter Cool! I'm Pleased we could get to the bottom of it. I was trying to make it more react-ish by removing state within sub-components and having it purely driven by top level data. It makes it slightly more complicated for small apps, but so much better for larger ones.
