### ISSUE TITLE
External non npm dependency for `react-utils`

### ISSUE THREAD

**Issue by og2t** [alexcurtis/react-treebeard#31]
Hi Alex,

We're using `react-treebeard` in a closed environment where we can't have refs to external (i.e. github) modules.

Would it be possible to integrate `react-utils` with`react-treebeard` or make it public in npm registry and reference that please?

I am talking about this line `"react-utils": "github:alexcurtis/react-utils",` in `package.json`

Many thanks!

**Comment by alexcurtis** [comment]
Hi. Yes, I'll get this sorted asap.

**Comment by og2t** [comment]
Thanks Alex.

**Comment by og2t** [comment]
Hi Alex! Have you had any time to look into this one please?

**Comment by alexcurtis** [comment]
This has been merged into the repo + published to npm.
