### ISSUE TITLE
Unable to npm install behind corporate proxy (dep react-utils)

### ISSUE THREAD

**Issue by Lilion12** [alexcurtis/react-treebeard#39]
Hi folks, 

I wanted to try the plugin to see if we could use it in one of our project but npm fails to fetch the project from github because ssh is not going through our corporate proxy. 

Here's a bit of the stacktrace : 
`npm ERR! Command failed: git -c core.longpaths=true clone --template=D:\Users\Clement.BTWNLCPSB69\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:alexcurtis/react-utils.git D:\Users\Clement.BTWNLCPSB69\AppData\Roaming\npm-cache\_git-remotes\git-github-com-alexcurtis-react-utils-git-ea67acf1
npm ERR! Cloning into bare repository 'D:\Users\Clement.BTWNLCPSB69\AppData\Roaming\npm-cache\_git-remotes\git-github-com-alexcurtis-react-utils-git-ea67acf1'...
npm ERR! ssh: connect to host github.com port 22: Connection refused
`

I don't really know what are the possibilities here, maybe publish the react-utils dependency in a proper npm repository? 

Quick fix is to use thethering to bypass the proxy but it's not viable! 

Cheers !

**Comment by alexcurtis** [comment]
@Lilion12 I am going to merge this into the project. I've been meaning to do this for a while. I'll try my best to get it done this evening (GMT).

**Comment by Lilion12** [comment]
Wonderful, thanks !

**Comment by gfx** [comment]
I'm looking forward to merging react-utils into the project in another reason: `npm shrinkwrap` in my project sometimes fails because of react-utils. I guess it is not registered to npm registry.

**Comment by alexcurtis** [comment]
This has been merged + published to npm. Credit goes to @gfx!
