### ISSUE TITLE
Can you have an array of "siblings" as the highest object in the data variable?

### ISSUE THREAD

**Issue by gbmhunter** [alexcurtis/react-treebeard#4]
Basically, I don't want to have a "root" or "react-treebeard" (as it is in the example) parent object in the data structure, but rather an array of siblings.

I have modified data into a structure that mimics this but react-treebeard doesn't seem to render it, indicating that this may not be supported?

**Comment by alexcurtis** [comment]
Yes. It can't do that at the moment. I will experiment with this today. My only concern is that with multiple siblings at the root -- its no longer a tree structure. But maybe that is ok, and only a use-case.

**Comment by gbmhunter** [comment]
Thanks! I think there could be many potential use cases. Just thinking of a common one, say displaying  folders/files on a computer, e.g. "My Computer" on Windows, displays multiple siblings, e.g. "C:\", "D:\", e.t.c in the same window. 

My use case is I'm displaying various categories (and sub-categories) of engineering calculators to the user. I want them to be able to click on a category (or sub-category) which will then filter the calculator results. It makes no sense for me to have a root level "Categories" folder, which is just extra and redundant information.

BTW, top job with this code, I am very impressed!

**Comment by alexcurtis** [comment]
@gbmhunter. I have published 1.0.11. This supports multiple root level nodes. You just need to pass your data in as an array -- rather than an object. I'll update the README to show this too.

**Comment by gbmhunter** [comment]
@alexcurtis , I will try it out soon...thank you so much!
