### ISSUE TITLE
Using without theme

### ISSUE THREAD

**Issue by a-x-** [alexcurtis/react-treebeard#45]
Can you make acceptable `theme={null}` and add classes on every nodes?

I want style by classic css way

**Comment by goodmorninggoaway** [comment]
@a-x- I just forked this to try implementing this.

**Comment by a-x-** [comment]
I swithed to `react-ui-tree` recently...

**Comment by ben174** [comment]
Why was this closed? Seems like a valid request.

**Comment by bartmin** [comment]
Doesn't
`style={{}}`
work?
