### ISSUE TITLE
Using <a href='javascript:;'> instead of <a href='#'>

### ISSUE THREAD

**Issue by bkniffler** [alexcurtis/react-treebeard#6]
Hey, would you consider switching href '#' to href 'javascript:;' in the header component? It is much safer to use.

**Comment by alexcurtis** [comment]
@bkniffler Hi. Yeah sure. I'd be interested to know why it is safer?

**Comment by bkniffler** [comment]
Under certain circumstances `#` will send you on top of the page, whereas `javascript:;` or `javascript:void(0);` won't do anything. Neither is great, but the second one is better. You could also think about not using <a/>.

More comments on this issue:
http://stackoverflow.com/questions/134845/href-attribute-for-javascript-links-or-javascriptvoid0
http://stackoverflow.com/questions/17789735/use-of-javascriptvoid0-v-s

**Comment by alexcurtis** [comment]
@bkniffler Thanks for clearing that up. Yes, I think we need to change this. Would you be able to submit this as a pull request please?

**Comment by alexcurtis** [comment]
@bkniffler I've released this under `1.0.12` in npm. Thanks for your help.

**Comment by bkniffler** [comment]
Hey, thanks. I just created another pull request without <a/>, you might think about this one as an alternative.
