### ISSUE TITLE
Is the project still maintained ?

### ISSUE THREAD

**Issue by sniphpet** [alexcurtis/react-treebeard#61]
Hello @alexcurtis ,

Is the project still maintained ? With the next release of react, `React.propTypes` will be deprecated in favor of the [prop-types packages](https://www.npmjs.com/package/prop-types).
Do you plan to upgrade ?

Thanks.

**Comment by alexcurtis** [comment]
@sniphpet Yes, this project is still being maintained. It has taken a back seat to other work recently, but I am going to start looking through the issue list and merging PRs as soon as I can (Within the next week). As part of this work, I intend to migrate prop types to the dependency.

**Comment by sniphpet** [comment]
Glad to hear it!
