### ISSUE TITLE
string refs are not supported on children of TransitionGroup and will be ignored

### ISSUE THREAD

**Issue by sicum** [alexcurtis/react-treebeard#72]
when click any part of tree show me this warning

browser.js:49 Warning: string refs are not supported on children of TransitionGroup and will be ignored. Please use a callback ref instead: https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute

**Comment by FlorianReich1986** [comment]
I have the same issue here

Warning: string refs are not supported on children of TransitionGroup and will be ignored. Please use a callback ref instead: [(https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute)]

Any ideas, how to fix this?

**Comment by ableli** [comment]
count me in. who can fix it ? the warning sick us.

**Comment by jeroenschieven** [comment]
This will be fixed after the pull request of #67 has been merged.

**Comment by izikorgad** [comment]
Hi,
Any ETA for a new release?
We are getting hundreds of warnings.

**Comment by MichaelDeBoey** [comment]
@izikorgad I'm talking to @alexcurtis about what he wants to do with the repo, ...
Hope to push this repo asap to npm, but don't have any ETA at the moment 😕

**Comment by MichaelDeBoey** [comment]
`v2.0.0`is [released](https://github.com/alexcurtis/react-treebeard/releases/tag/v2.0.0) as of now! 🙂
