### ISSUE TITLE
velocity-react & lodash

### ISSUE THREAD

**Issue by faiwer** [alexcurtis/react-treebeard#74]
Hello. I've installed the react-treebeard package by `npm install react-treebeard --save` command. But after including it by `import` keyword I got:
```
/~/velocity-react/velocity-component.js
Module not found: Error: Can't resolve 'lodash/collection/forEach' in '/home/faiwer/www/bilim/constructor/node_modules/velocity-react'
 @ ./~/velocity-react/velocity-component.js 73:11-47
 @ ./~/velocity-react/index.js
 @ ./~/react-treebeard/lib/components/decorators.js
 @ ./~/react-treebeard/lib/index.js
 @ ./~/react-treebeard/index.js
```
I'm already using `lodash` library. Do I need to use another version?

**Comment by faiwer** [comment]
Also I've found one staaange [solution](https://stackoverflow.com/questions/41745082/cannot-resolve-velocity-react-because-of-lodash-dependencies-not-being-found). It is alrering the resolve.alias section by:
```
'lodash/object/omit': 'lodash/omit',
'lodash/object/extend': 'lodash/extend',
'lodash/lang/isObject': 'lodash/isObject',
'lodash/lang/isEqual': 'lodash/isEqual',
'lodash/collection/forEach': 'lodash/forEach',
'lodash/collection/each': 'lodash/each',
'lodash/collection/pluck': 'lodash/map',
'lodash/object/keys': 'lodash/keys',
```

**Comment by ahmed1490** [comment]
+1

**Comment by sulfurious** [comment]
Try changing your resolve modules from `path.resolve(__dirname, "node_modules")` to just `"node_modules"`

https://github.com/webpack/webpack/issues/4030

**Comment by bsara** [comment]
@sulfurious that fixed it, you're a rock star.
