### ISSUE TITLE
react 15.5 compatibility 

### ISSUE THREAD

**Issue by n-b-c2vx** [alexcurtis/react-treebeard#81]
commit 832d81278b10ec88e0aecc32b4811aa42fe035cc included compatibility for react 15.5. Are there any plans to create a release from after this commit and publish to npm?

**Comment by MichaelDeBoey** [comment]
As I already told in [#72 (comment)](https://github.com/alexcurtis/react-treebeard/issues/72#issuecomment-314223738), I'm currently talking to @alexcurtis about what he wants to do with the repo, ...
Hope to push this repo asap to npm, but don't have any ETA at the moment 😕

**Comment by MichaelDeBoey** [comment]
`v2.0.0`is [released](https://github.com/alexcurtis/react-treebeard/releases/tag/v2.0.0) as of now! 🙂
