### ISSUE TITLE
Travis tests fail

### ISSUE THREAD

**Issue by MichaelDeBoey** [alexcurtis/react-treebeard#82]
The Travis tests [are failing](https://travis-ci.org/alexcurtis/react-treebeard/builds/254645178) even tho the local tests are passing 😕

Any idea how this has happened?

**Comment by MichaelDeBoey** [comment]
@igor-dv Maybe you have an idea for this one?

**Comment by igor-dv** [comment]
@alexcurtis 
As you can see in `src\components\header.js`, there are several places that use `Object.assign`, which is not supported in Firefox v31:

![image](https://user-images.githubusercontent.com/7867954/28328264-ac9c0096-6bee-11e7-9517-4410a7391a19.png)

Only in v[34](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

Babel is not configured to handle `Object.assign`, as for example it does for the spread operator here: 
```jsx
 <VelocityTransitionGroup {...restAnimationInfo} ></VelocityTransitionGroup>
```

If you will change the `.babelrc` to use polyfill, it will bring `babel-runtime/core-js/object/assign` instead. 

I assume that the old `.babelrc` did it by default..

**Comment by igor-dv** [comment]
Just installed the 1.1.0 version and there is indeed a polyfill here.
