### ISSUE TITLE
Expanding/Collapsing wrong item

### ISSUE THREAD

**Issue by rameshvishnoi90904** [alexcurtis/react-treebeard#97]
i am click on themes folder but default,js is highlighted/active

![image](https://user-images.githubusercontent.com/13585002/30480679-a7091894-9a38-11e7-9f64-eb32950ef996.png)

**Comment by rameshvishnoi90904** [comment]
Anyone monitoring issue?

**Comment by MichaelDeBoey** [comment]
Close in favor of #58
